# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3955c80c995ddbf8cf4b869bea8bc41b532dd8b2b1b527586b37a8cc3b1701a9cabf58a4ebce90d99aaedc983917320973d72865b8478d574b14eb510e2a3607

test:
  secret_key_base: 26470ce8284facc7bcbc0c2e71f9330aacf961d9c9a9278592a1cb6dd62a8701c8e9d97761d78f20c833cb966b8782f38c51e3b9fde62a94f75b4bafbb054c80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
